Update downloads page
haskell-infra/www.haskell.org pull request #129
Opened 2021-08-13 06:46 UTC by tomjaguarpaw

Minor edits to https://github.com/haskell-infra/www.haskell.org/pull/125 of two types:

* Fix minor typos
* Replace "here" as link text with text describing the link target

I suggest that #125 be replaced with this.

2021-08-13 17:24 UTC, hasufell requested changes
I'd suggest to omit that ghcup can do stack installations for now. Experimental options don't need to be promoted. Either we stand behind it or we don't.

2021-08-13 17:24 UTC, hasufell commented on downloads.markdown
> +   GHC, cabal-install, haskell-language-server and (experimentally) stack.
I'd omit stack here

```suggestion
   GHC, cabal-install and haskell-language-server
```

2021-08-13 17:24 UTC, hasufell commented on downloads.markdown
> +2. Stack can be also installed directly as described on
```suggestion
2. Stack can be installed as described on
```

2021-08-14 15:40 UTC, tomjaguarpaw commented
Closing because pushed to https://github.com/haskell-infra/www.haskell.org/pull/125

2021-08-14 15:40 UTC, closed without merging